SELECT
    r.id AS Id,
    r.created_at AS CreatedAt,
    rp.raw_kind AS RawKind,
    rp.source_uri AS SourceUri,
    rp.internal_path AS InternalPath,
    r.persistence_policy AS PersistencePolicy,
    rp.source_last_modified_at AS SourceLastModifiedAt,
    rp.source_app_hint AS SourceAppHint,
    rp.captured_at AS CapturedAt,
    rp.original_suggested_name AS OriginalSuggestedName,
    r.original_file_name AS OriginalFileName,
    r.mime_type AS MimeType,
    r.file_size AS FileSize,
    r.source AS Source,
    pp.processed_file_path AS ProcessedFilePath,
    pp.processed_text AS ProcessedText,
    pp.route_id AS ProcessedRouteId,
    r.thumbnail_path AS ThumbnailPath,
    r.summary AS Summary,
    r.condition_tags_json AS ConditionTags,
    r.title_override AS TitleOverride,
    r.annotations AS Annotations,
    r.property_tags_json AS PropertyTags,
    r.privacy AS Privacy,
    r.sync_policy AS SyncPolicy,
    r.sync_target_devices_json AS SyncTargetDevices,
    r.processing_model AS ProcessingModel,
    r.permission_preset_id AS PermissionPresetId,
    r.state AS State,
    r.waiting_expires_at AS WaitingExpiresAt,
    r.last_error AS LastError,
    r.feature_hash AS FeatureHash,
    r.health_json AS Health
FROM resources r
LEFT JOIN resource_raw_payloads rp ON rp.resource_id = r.id
LEFT JOIN resource_processed_payloads pp ON pp.resource_id = r.id