INSERT INTO resources (
    id, created_at, raw_kind, source_uri, internal_path, persistence_policy,
    source_last_modified_at, source_app_hint, captured_at, original_suggested_name,
    original_file_name, mime_type, file_size, source,
    processed_route_id, processed_file_path, processed_text,
    thumbnail_path, summary,
    condition_tags_json, title_override, annotations, property_tags_json,
    privacy, sync_policy, sync_target_devices_json, processing_model,
    permission_preset_id, state, waiting_expires_at, last_error,
    feature_hash, health_json)
VALUES (
    @Id, @CreatedAt, @RawKind, @SourceUri, @InternalPath, @PersistencePolicy,
    @SourceLastModifiedAt, @SourceAppHint, @CapturedAt, @OriginalSuggestedName,
    @OriginalFileName, @MimeType, @FileSize, @Source,
    @ProcessedRouteId, @ProcessedFilePath, @ProcessedText,
    @ThumbnailPath, @Summary,
    @ConditionTags, @TitleOverride, @Annotations, @PropertyTags,
    @Privacy, @SyncPolicy, @SyncTargetDevices, @ProcessingModel,
    @PermissionPresetId, @State, @WaitingExpiresAt, @LastError,
    @FeatureHash, @Health)
ON CONFLICT(id) DO UPDATE SET
    created_at = excluded.created_at,
    raw_kind = excluded.raw_kind,
    source_uri = excluded.source_uri,
    internal_path = excluded.internal_path,
    persistence_policy = excluded.persistence_policy,
    source_last_modified_at = excluded.source_last_modified_at,
    source_app_hint = excluded.source_app_hint,
    captured_at = excluded.captured_at,
    original_suggested_name = excluded.original_suggested_name,
    original_file_name = excluded.original_file_name,
    mime_type = excluded.mime_type,
    file_size = excluded.file_size,
    source = excluded.source,
    processed_route_id = excluded.processed_route_id,
    processed_file_path = excluded.processed_file_path,
    processed_text = excluded.processed_text,
    thumbnail_path = excluded.thumbnail_path,
    summary = excluded.summary,
    condition_tags_json = excluded.condition_tags_json,
    title_override = excluded.title_override,
    annotations = excluded.annotations,
    property_tags_json = excluded.property_tags_json,
    privacy = excluded.privacy,
    sync_policy = excluded.sync_policy,
    sync_target_devices_json = excluded.sync_target_devices_json,
    processing_model = excluded.processing_model,
    permission_preset_id = excluded.permission_preset_id,
    state = excluded.state,
    waiting_expires_at = excluded.waiting_expires_at,
    last_error = excluded.last_error,
    feature_hash = excluded.feature_hash,
    health_json = excluded.health_json;