INSERT INTO resources (
    id, created_at, persistence_policy, original_file_name, mime_type, file_size, source,
    thumbnail_path, summary,
    condition_tags_json, title_override, annotations, property_tags_json,
    privacy, sync_policy, sync_target_devices_json, processing_model,
    permission_preset_id, state, waiting_expires_at, last_error,
    feature_hash, health_json)
VALUES (
    @Id, @CreatedAt, @PersistencePolicy, @OriginalFileName, @MimeType, @FileSize, @Source,
    @ThumbnailPath, @Summary,
    @ConditionTags, @TitleOverride, @Annotations, @PropertyTags,
    @Privacy, @SyncPolicy, @SyncTargetDevices, @ProcessingModel,
    @PermissionPresetId, @State, @WaitingExpiresAt, @LastError,
    @FeatureHash, @Health)
ON CONFLICT(id) DO UPDATE SET
    created_at = excluded.created_at,
    persistence_policy = excluded.persistence_policy,
    original_file_name = excluded.original_file_name,
    mime_type = excluded.mime_type,
    file_size = excluded.file_size,
    source = excluded.source,
    thumbnail_path = excluded.thumbnail_path,
    summary = excluded.summary,
    condition_tags_json = excluded.condition_tags_json,
    title_override = excluded.title_override,
    annotations = excluded.annotations,
    property_tags_json = excluded.property_tags_json,
    privacy = excluded.privacy,
    sync_policy = excluded.sync_policy,
    sync_target_devices_json = excluded.sync_target_devices_json,
    processing_model = excluded.processing_model,
    permission_preset_id = excluded.permission_preset_id,
    state = excluded.state,
    waiting_expires_at = excluded.waiting_expires_at,
    last_error = excluded.last_error,
    feature_hash = excluded.feature_hash,
    health_json = excluded.health_json;